-- NPS guide table for Supabase
-- Run this in Supabase SQL Editor before deploying the site.

create table if not exists "NPS" (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  description text,
  content text,
  link text,
  author text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table "NPS" enable row level security;

drop policy if exists "Allow public read" on "NPS";
drop policy if exists "Allow public insert" on "NPS";
drop policy if exists "Allow public update" on "NPS";
drop policy if exists "Allow public delete" on "NPS";

create policy "Allow public read"
on "NPS"
for select
using (true);

create policy "Allow public insert"
on "NPS"
for insert
with check (true);

create policy "Allow public update"
on "NPS"
for update
using (true);

create policy "Allow public delete"
on "NPS"
for delete
using (true);

-- Optional sample data. 필요하면 주석 해제 후 실행하세요.
-- insert into "NPS" (category, title, description, content, link, author)
-- values
-- ('제작 시 참고사항', '광고주 선호/비선호 소재 기준', '네플스 소재 제작 시 광고주가 선호하는 구성과 지양해야 하는 표현을 정리했습니다.', '혜택/숫자 강조 소재 선호\n요소가 너무 많은 소재 지양\n룰렛/버튼 등 사행성 느낌 지양', '', '송이'),
-- ('피그마 꿀팁', '텍스트 일괄 변경', '날짜, 캠페인명, 문구를 한 번에 변경하는 방법입니다.', 'Ctrl + F 실행\nReplace 선택\n기존 텍스트 입력\n변경할 텍스트 입력\nReplace all 클릭', '', '송이');
